export enum ActionTypes {
  SET_CHAT_SESSION = 'SET_CHAT_SESSION',
  CHATTER_JOINED = 'CHATTER_JOINED',
  CHATTER_LEFT = 'CHATTER_LEFT',
  SET_CHATTERS = 'SET_CHATTERS',
  NEW_MESSAGE = 'SET_NEW_MESSAGE',
  SET_USER = 'SET_USER',
  SET_IP = 'SET_IP',
  SET_ADDRESS = 'SET_ADDRESS',
  SET_GEOCODE = 'SET_GEOCODE',
  SET_CHATTER_DISTANCE = 'SET_CHATTER_DISTANCE',
}
