# Generated by Django 3.0.6 on 2020-05-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatter',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
